### PR TITLE
URA-103 - New panels and transcripts

### LINKED ISSUE #12: Index info fields
rather than assuming the order of the fields it would be more robust to index these from the header

```
info_cols = [
        'GENE', 'VARIANT_CLASS', 'CONS', 'EXON', 'HGVSc',
        'HGVSp', 'gnomAD_AF', 'SIFT', 'POLYPHEN', 'DB'
```

### PR DESCRIPTION
**Pull request by jethror1**
- Addition of new T_NHL and plasma cell myeloma panels
- Addition of 15 new genes to accommodate new capture design
- Change of transcript for BCORL1, KRAS, CUX1, FBXW7 and GNAS
- Update to use of 2 transcripts for CUX1 and GNAS
- Full transcript list [here](https://cuhbioinformatics.atlassian.net/wiki/spaces/URA/pages/2646933524/Final+list+of+genes+to+transcripts+for+HaemOnc+version+2+panel)
- Fixes #12 through use of `+split-vep` and additional [split_info()](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/853014d4140ada92695dc275ac6b2fdeee2499dc/resources/home/dnanexus/vcf_handler.py#L200) function in `vcf_handler.py`

Example job: https://platform.dnanexus.com/projects/G97PGQj4fqQ0k395Fkzg8Bg4/monitor/job/G9kk77j4fqQJ0q9Z2Kkpyfx1

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/39)

### CODE REVIEW

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/39)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @Aisha-D and @jethror1)

___
*[`src/code.sh` line 123 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/39#-N1PDQ5d8OTQWZzl8O4X:-N1PDQ5d8OTQWZzl8O4Y:by8jone) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/0ed7a61eba2ae3816f5ec87ee41d48054984a93f/src/code.sh#L123)):*
> ```Shell
> 	splitfile="${mutect2_vcf_prefix}_split.vcf"
> 
> 	time bedtools intersect -header -u -a "${mutect2_vcf_path}" -b "${mutect2_bed_path}" \
> ```

why is the "-u" parameter added? 
___
*[`src/code.sh` line 203 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/39#-N1PLDWaADDC4yoouCZz:-N1PLDWaADDC4yoouC_-:b-i78300) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/0ed7a61eba2ae3816f5ec87ee41d48054984a93f/src/code.sh#L203)):*
> ```Shell
> 	NM_001136023.,NM_005475.,NM_002834.,NM_004119.,NM_002168.,NM_004380.,NM_000546.,NM_001042492.,\
> 	NM_012448.,NM_139276.,NM_003620.,NM_001195427.,NM_015559.,NM_004343.,NM_004364.,NM_015338.,NM_080425.,NM_016592.,\
> 	NM_00175.,NM_006758.,NM_001429.,NM_005089.,NM_001123385.,NM_002049.,NM_001042750.,\
> ```

Missing 4 on the end -> Should be NM_001754

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/39)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @Aisha-D and @jethror1)

___
*[`src/code.sh` line 81 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/39#-N1PPFXi0ZMXbY10UOeJ:-N1PPFXi0ZMXbY10UOeK:b-4ndcw8) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/0ed7a61eba2ae3816f5ec87ee41d48054984a93f/src/code.sh#L81)):*
> ```Shell
> }
> 
> function split_vep {
> ```

could this not be done within filter function rather than calling the function after each filter vcf?

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/39)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @Aisha-D and @jethror1)

___
*[`src/code.sh` line 212 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/39#-N1PPjmzCwqis3X08SqO:-N1PPjn-8lK29aKEzwoH:b7j0y7j) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/0ed7a61eba2ae3816f5ec87ee41d48054984a93f/src/code.sh#L212)):*
> ```Shell
> 	annotate_vep_vcf "$splitfile" "$splitvepfile"
> 
> 	# split VCF annotation to separate records where more than one transcript of annotation is present
> ```

could this be moved to inside the function? and dont think last line in needed anymore?

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/39)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @Aisha-D and @jethror1)

___
*[`resources/home/dnanexus/vcf_handler.py` line 307 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/39#-N1PRB6w5CnLf5ZeLnKM:-N1PRB6w5CnLf5ZeLnKN:b-k7l3iv) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/0ed7a61eba2ae3816f5ec87ee41d48054984a93f/resources/home/dnanexus/vcf_handler.py#L307)):*
> ```Python
>         ]] = pd.NA
> 
>         # set order
> ```

Does pandas not order when creating empty df :o  ? Also is it possible to order once, cause this is ordered again down further down.

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/39)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @Aisha-D)

___
*[`resources/home/dnanexus/vcf_handler.py` line 307 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/39#-N1PRB6w5CnLf5ZeLnKM:-N1bxcfy3z9VOBKwmGgA:bxgpfyu) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/0ed7a61eba2ae3816f5ec87ee41d48054984a93f/resources/home/dnanexus/vcf_handler.py#L307)):*
<details><summary><i>Previously, Aisha-D wrote…</i></summary><blockquote>

Does pandas not order when creating empty df :o  ? Also is it possible to order once, cause this is ordered again down further down.
</blockquote></details>

by set order I am just ordering the columns, there's already some columns there that I'm adding to so I add them and then order. Also as this is empty I return it after this instead of continuing further so can't rely on the other ordering
___
*[`src/code.sh` line 81 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/39#-N1PPFXi0ZMXbY10UOeJ:-N1bxwRY6LeMxXGV6aKb:b-eoijb5) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/0ed7a61eba2ae3816f5ec87ee41d48054984a93f/src/code.sh#L81)):*
<details><summary><i>Previously, Aisha-D wrote…</i></summary><blockquote>

could this not be done within filter function rather than calling the function after each filter vcf?
</blockquote></details>

that would make sense, tired me didn't think to do that, changed it
___
*[`src/code.sh` line 123 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/39#-N1PDQ5d8OTQWZzl8O4X:-N1byVGz16NfnhmvrRS8:b-mhe03a) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/0ed7a61eba2ae3816f5ec87ee41d48054984a93f/src/code.sh#L123)):*
<details><summary><i>Previously, Aisha-D wrote…</i></summary><blockquote>

why is the "-u" parameter added? 
</blockquote></details>

because of multiple transcripts we can get duplicate variants when intersecting (from having the same regions in the bed file), `-u` will just return one which will then get both transcript annotation and split with `+split-vep`. If not we would get 2 variants annotated with both transcripts which would then end up with 4 records
___
*[`src/code.sh` line 203 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/39#-N1PLDWaADDC4yoouCZz:-N1bz24A-YkuZ32qVpg3:b-vkmpuu) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/0ed7a61eba2ae3816f5ec87ee41d48054984a93f/src/code.sh#L203)):*
<details><summary><i>Previously, Aisha-D wrote…</i></summary><blockquote>

Missing 4 on the end -> Should be NM_001754
</blockquote></details>

you the best, my eyes have merged all of these into one
___
*[`src/code.sh` line 212 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/39#-N1PPjmzCwqis3X08SqO:-N1bzBzJ6x8DxWflc1KJ:b-yuy5kw) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/0ed7a61eba2ae3816f5ec87ee41d48054984a93f/src/code.sh#L212)):*
<details><summary><i>Previously, Aisha-D wrote…</i></summary><blockquote>

could this be moved to inside the function? and dont think last line in needed anymore? 
</blockquote></details>

yeah forgot to remove this, done

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/39)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @Aisha-D and @jethror1)

___
*[`src/code.sh` line 123 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/39#-N1PDQ5d8OTQWZzl8O4X:-N1c9yMq5aFO36rfN0GV:blomo7z) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/0ed7a61eba2ae3816f5ec87ee41d48054984a93f/src/code.sh#L123)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

because of multiple transcripts we can get duplicate variants when intersecting (from having the same regions in the bed file), `-u` will just return one which will then get both transcript annotation and split with `+split-vep`. If not we would get 2 variants annotated with both transcripts which would then end up with 4 records
</blockquote></details>

Ahh makes sense, can this pls be added as a comment so if someone (probably me) wants to look at this code some time later it'll be clear that the -u is to handle multiple transcripts?

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/39)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @Aisha-D)

___
*[`src/code.sh` line 123 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/39#-N1PDQ5d8OTQWZzl8O4X:-N1cCvl7Bwp76PBYCdxK:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/0ed7a61eba2ae3816f5ec87ee41d48054984a93f/src/code.sh#L123)):*
<details><summary><i>Previously, Aisha-D wrote…</i></summary><blockquote>

Ahh makes sense, can this pls be added as a comment so if someone (probably me) wants to look at this code some time later it'll be clear that the -u is to handle multiple transcripts?
</blockquote></details>

Done.

**Review by Aisha-D — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/39#-:-N1cNkQrDEcZBrkHjTKT:bnfp4nl)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @Aisha-D)

**Pull request merged**
