### PR TITLE
v2.2.0

### LINKED ISSUE #15: Better design
- Consider refactoring how VEP is called
- Consider parallelising VEP/docker, e.g. https://stackoverflow.com/questions/56040426/parallel-code-execution-in-docker-containers
- Alternatively, annotate once and transcript/panel filter many times

### LINKED ISSUE #17: Run VEP in offline mode
`--cached` mode can still connect to ensembl so add `--offline`

### LINKED ISSUE #18: Utilise more cores
Could we consider adding `--fork` to the VEP commands to speed things up? It only looks to be using 1/4 cores currently.

More details: https://m.ensembl.org/info/docs/tools/vep/script/vep_other.html#faster

### PR DESCRIPTION
**Pull request by jethror1**
- addition of --offline to calls to VEP annotate, prevents VEP from attempting to connect to their servers which are intermittently down and have caused jobs to fail
  - fixes #17 
- refactor VEP annotation and filtering to single functions and function calls for each VCF
  - single call to annotate whole VCF then filter by transcript lists has reduced run time by ~50%
  - fixes #15 
- make MAF file a separate app input and remove from tarball 
- create new up to date MAF file to reflect most recent NovaSeq samples, documented [here](https://cuhbioinformatics.atlassian.net/wiki/spaces/URA/pages/2415591443/Creation+of+Myeloid+NovaSeq+samples+MAF+file)
- closes #18 - not applicable for this use case
- full testing of changes documented [here](https://cuhbioinformatics.atlassian.net/wiki/spaces/URA/pages/2410348566/Update+eggd+vcf+handler+for+uranus+v2.1.0+-+v2.2.0)

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/20)

### CODE REVIEW

**Review by woook — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/20)* status: 1 of 4 files reviewed, 6 unresolved discussions (waiting on @jethror1 and @woook)

___
*[dxapp.json, line 2 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/20#-MluKmR5--5e-GUnKApb:-MluKmR5--5e-GUnKApc:b-tdfo1n) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/61dd9a5aa566ac6deca6a5afa0439811b248b77d/dxapp.json#L2)):*
> ```
> v2.2.0
> ```
As versions are metadata for apps, I don't think we want the version in the name (or title)
___
*[Readme.md, line 20 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/20#-MluLCFF7BBl0g-YrRIA:-MluLCFF7BBl0g-YrRIB:b-w618a5) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/61dd9a5aa566ac6deca6a5afa0439811b248b77d/Readme.md#L20)):*
> ```
> X
> ```
Don't you want to put the actual number here?
___
*[src/code.sh, line 38 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/20#-MluPDNV6E1Dg-b_AKJH:-MluPDNV6E1Dg-b_AKJI:b-dyqywt) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/61dd9a5aa566ac6deca6a5afa0439811b248b77d/src/code.sh#L38)):*
> ```
> Function to filter annotated VCF with VEP to retain variants with AF < 0.10 in gnomAD
> ```
This is a partial description
___
*[src/code.sh, line 64 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/20#-MluPgsK315cEhX4LEeA:-MluPgsK315cEhX4LEeB:b-p1w4cq) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/61dd9a5aa566ac6deca6a5afa0439811b248b77d/src/code.sh#L64)):*
> ```
> SYMBOL
> ```
Why was this filter added? Does it do anything considering the transcript matching?
___
*[src/code.sh, line 171 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/20#-MluTHkGAR6wMc0mwcro:-MluTHkGAR6wMc0mwcrp:bu57byt) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/61dd9a5aa566ac6deca6a5afa0439811b248b77d/src/code.sh#L171)):*
> ```
> 	cll_transcripts="NM_001165.,NM_004333.,NM_033632.,NM_005343.,NM_033360.,NM_002468.,NM_017617.,\
> 	NM_002524.,NM_012433.,NM_000546."
> ```
You missed NM_000051
___
*[src/code.sh, line 235 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/20#-MluVM--1VKd1AjF9eaV:-MluVM--1VKd1AjF9eaW:bm2lvgu) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/61dd9a5aa566ac6deca6a5afa0439811b248b77d/src/code.sh#L235)):*
> ```
> ·
> ```
ws

**Review by woook — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/20)* status: 1 of 4 files reviewed, 9 unresolved discussions (waiting on @jethror1 and @woook)

___
*[src/code.sh, line 50 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/20#-MluWaGe2SM1WM4c6IWU:-MluWaGe2SM1WM4c6IWV:b9gz40t) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/61dd9a5aa566ac6deca6a5afa0439811b248b77d/src/code.sh#L50)):*
> ```
> "$transcript_list" | sed 's/[[:space:]]//g'
> ```
https://github.com/koalaman/shellcheck/wiki/SC2001
___
*[src/code.sh, line 54 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/20#-MluWhWOBhZrXIfQMTqi:-MluWhWP-DRZvbxVF60J:buyaxu5) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/61dd9a5aa566ac6deca6a5afa0439811b248b77d/src/code.sh#L54)):*
> ```
> "$transcript_list" | sed 's/\./\\./g'
> ```
https://github.com/koalaman/shellcheck/wiki/SC2001
___
*[src/code.sh, line 57 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/20#-MluWjLa00u3nnTsn0Ex:-MluWjLa00u3nnTsn0Ey:b-y2gean) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/61dd9a5aa566ac6deca6a5afa0439811b248b77d/src/code.sh#L57)):*
> ```
> "$transcript_list" | sed 's/,/ or Feature match /g'
> ```
https://github.com/koalaman/shellcheck/wiki/SC2001

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/20)* status: 1 of 4 files reviewed, 9 unresolved discussions (waiting on @jethror1 and @woook)

___
*[src/code.sh, line 38 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/20#-MluPDNV6E1Dg-b_AKJH:-MluYI-c0gzfDUeG-ySU:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/61dd9a5aa566ac6deca6a5afa0439811b248b77d/src/code.sh#L38)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

> ```
> Function to filter annotated VCF with VEP to retain variants with AF < 0.10 in gnomAD
> ```
This is a partial description
</blockquote></details>

Done.
___
*[src/code.sh, line 50 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/20#-MluWaGe2SM1WM4c6IWU:-MluXvgA5QnYG18AZHZC:bxmybmg) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/61dd9a5aa566ac6deca6a5afa0439811b248b77d/src/code.sh#L50)):*
> [[:space:]]
that does seem simpler, not really sure why I went for sed over expansion.
Is this a skinning a cat situation where neither is correct/wrong? If we change these shouldn't we then retest (which I'd rather not do :) ) 
___
*[src/code.sh, line 54 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/20#-MluWhWOBhZrXIfQMTqi:-MluYIxl0rnfsWeVhPIH:b-9chp70) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/61dd9a5aa566ac6deca6a5afa0439811b248b77d/src/code.sh#L54)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

> ```
> "$transcript_list" | sed 's/\./\\./g'
> ```
https://github.com/koalaman/shellcheck/wiki/SC2001
</blockquote></details>

as above
___
*[src/code.sh, line 57 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/20#-MluWjLa00u3nnTsn0Ex:-MluYJxv1xge0HavegAH:b-9chp70) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/61dd9a5aa566ac6deca6a5afa0439811b248b77d/src/code.sh#L57)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

> ```
> "$transcript_list" | sed 's/,/ or Feature match /g'
> ```
https://github.com/koalaman/shellcheck/wiki/SC2001
</blockquote></details>

as above
___
*[src/code.sh, line 64 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/20#-MluPgsK315cEhX4LEeA:-MluWvir4MK4fteyg8L2:b-mq2ju6) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/61dd9a5aa566ac6deca6a5afa0439811b248b77d/src/code.sh#L64)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

> ```
> SYMBOL
> ```
Why was this filter added? Does it do anything considering the transcript matching?
</blockquote></details>

Because you did: https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/da0d046de67d6f3ebf1e2877658bd3c0832990ac/src/code.sh#L251

It filters records where a symbol is present: https://m.ensembl.org/info/docs/tools/vep/script/vep_filter.html
___
*[src/code.sh, line 171 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/20#-MluTHkGAR6wMc0mwcro:-MluYww8-b_7XmTARCms:bmqvw54) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/61dd9a5aa566ac6deca6a5afa0439811b248b77d/src/code.sh#L171)):*
> NM_000051
well that isn't good, I've added it now

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/20)* status: 1 of 4 files reviewed, 9 unresolved discussions (waiting on @jethror1 and @woook)

___
*[src/code.sh, line 235 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/20#-MluVM--1VKd1AjF9eaV:-MluZOmdDy6sFhKZLA53:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/61dd9a5aa566ac6deca6a5afa0439811b248b77d/src/code.sh#L235)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

> ```
> ·
> ```
ws
</blockquote></details>

Done.

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/20)* status: 1 of 4 files reviewed, 9 unresolved discussions (waiting on @jethror1 and @woook)

___
*[Readme.md, line 20 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/20#-MluLCFF7BBl0g-YrRIA:-Mlu_IehDhoZxxDIK720:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/61dd9a5aa566ac6deca6a5afa0439811b248b77d/Readme.md#L20)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

> ```
> X
> ```
Don't you want to put the actual number here?
</blockquote></details>

Done.

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/20)* status: 1 of 4 files reviewed, 9 unresolved discussions (waiting on @woook)

___
*[dxapp.json, line 2 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/20#-MluKmR5--5e-GUnKApb:-Mlu_WDr3GuPvTuGdJrK:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/61dd9a5aa566ac6deca6a5afa0439811b248b77d/dxapp.json#L2)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

> ```
> v2.2.0
> ```
As versions are metadata for apps, I don't think we want the version in the name (or title)
</blockquote></details>

Done.

**Review by woook — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/20)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @jethror1 and @woook)

___
*[src/code.sh, line 64 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/20#-MluPgsK315cEhX4LEeA:-Mlua5SpEJq2XGT1u4ME:b-srve9g) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/61dd9a5aa566ac6deca6a5afa0439811b248b77d/src/code.sh#L64)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

Because you did: https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/da0d046de67d6f3ebf1e2877658bd3c0832990ac/src/code.sh#L251

It filters records where a symbol is present: https://m.ensembl.org/info/docs/tools/vep/script/vep_filter.html
</blockquote></details>

This feels redundant as if it's got a transcript, it will also have a symbol. 
Probably should got rid of it previously...
Can we remove please.

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/20)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @woook)

___
*[src/code.sh, line 64 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/20#-MluPgsK315cEhX4LEeA:-MlumSl58AnRGBch-h2_:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/61dd9a5aa566ac6deca6a5afa0439811b248b77d/src/code.sh#L64)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

This feels redundant as if it's got a transcript, it will also have a symbol. 
Probably should got rid of it previously...
Can we remove please.
</blockquote></details>

Done.

**Review by woook — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/20)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jethror1)

**Pull request merged**
