### PR TITLE
Changes for v1.5.0

### PR DESCRIPTION
**Pull request by woook**
- Added excel workbook output with variants for each panel in separate sheets
- Removed synonymous variant filter
- Prefix exon numbers with the word exon to overcome excel
- Switch out gnomad for VAF in report_text
- Further report_text formatting
- Renamed mutect2_vcf_2_BSVI_v1.2.0.py to vcf_handler.py to better reflect it's evolved current state

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/11)

### CODE REVIEW

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 2 files at r2, 2 of 3 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/11)* status: all files reviewed, 4 unresolved discussions (waiting on @woook)

___
*[.gitignore, line 1 at r7](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/11#-MZY6zB6AN40STthJARs:-MZY6zB6AN40STthJARt:bet3z2g) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/ae7ae9604a4d97627799bbe204d5da7977a22a05/.gitignore#L1)):*
> ```
> resources/home/dnanexus/uranus_vcf_handler_eh.py
> ```
What's this for?
___
*[resources/home/dnanexus/vcf_handler.py, line 65 at r7](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/11#-MZY0WIN0pXmfkAnEeX7:-MZY0WIN0pXmfkAnEeX8:b6xcx1r) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/ae7ae9604a4d97627799bbe204d5da7977a22a05/resources/home/dnanexus/vcf_handler.py#L65)):*
> ```
> returns header as a list for output (bsvi) vcf
> ```
This returns more than just the header, description is incomplete
___
*[resources/home/dnanexus/vcf_handler.py, line 158 at r7](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/11#-MZY2VaXD2g2YpEkIMJB:-MZY2VaXD2g2YpEkIMJC:b-5rac2s) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/ae7ae9604a4d97627799bbe204d5da7977a22a05/resources/home/dnanexus/vcf_handler.py#L158)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>     info_cols = [
>         'GENE', 'VARIANT_CLASS', 'CONS', 'EXON', 'HGVSc',
>         'HGVSp', 'gnomAD_AF', 'SIFT', 'POLYPHEN', 'DB'
>     ]
> ```
</details>

More robust to index the field order from the header definition of CSQ then access values using that index, just in case we update VEP in the future and the order changes
___
*[resources/home/dnanexus/vcf_handler.py, line 179 at r7](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/11#-MZY3MTJ3Xp9A_AiC8JV:-MZY3MTJ3Xp9A_AiC8JW:b-ypotr5) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/ae7ae9604a4d97627799bbe204d5da7977a22a05/resources/home/dnanexus/vcf_handler.py#L179)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>     # get AF values from sample column add to new AF column, convert to %
>     af_index = af_index[0]
>     af_values = vcf_df['SAMPLE'].apply(lambda x: x.split(':')[af_index]).apply(
>         lambda x: '{:.1%}'.format(float(x)))
>     vcf_df.insert(11, 'AF', af_values)
> ```
</details>

Do we want to store a % in a field labelled AF? ( it's allele fraction, not allele percentage)
AF is a reserved key with a specific definition: https://samtools.github.io/hts-specs/VCFv4.3.pdf Page 8

**Review by woook — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/11)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @mattgarner)

___
*[.gitignore, line 1 at r7](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/11#-MZY6zB6AN40STthJARs:-MZYZ6loEYyr_lkslDKw:b-b63vwc) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/ae7ae9604a4d97627799bbe204d5da7977a22a05/.gitignore#L1)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> resources/home/dnanexus/uranus_vcf_handler_eh.py
> ```
What's this for?
</blockquote></details>

No idea_eh
Maybe it's Canadian?
___
*[resources/home/dnanexus/vcf_handler.py, line 65 at r7](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/11#-MZY0WIN0pXmfkAnEeX7:-MZYZyybANDStACnFcHX:bfr9v39) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/ae7ae9604a4d97627799bbe204d5da7977a22a05/resources/home/dnanexus/vcf_handler.py#L65)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> returns header as a list for output (bsvi) vcf
> ```
This returns more than just the header, description is incomplete
</blockquote></details>

Some git confusion here, current version doesn't say this
```
def mod_genotype(vcf_df):
    """
    Overwrite GT with 0/1 when it's derived from a multiallelic
    e.g. 0/0/1/0 -> 0/1 and 0/0/0/1 -> 0/1
    Args:
        - input_vcf (file): vcf file passed at cmd line
    Returns:
        - vcf_df (df): df of variants with modified genotype
    """
```
___
*[resources/home/dnanexus/vcf_handler.py, line 158 at r7](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/11#-MZY2VaXD2g2YpEkIMJB:-MZY_H3k3cGxWwQTrCoo:bprra3o) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/ae7ae9604a4d97627799bbe204d5da7977a22a05/resources/home/dnanexus/vcf_handler.py#L158)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
>     info_cols = [
>         'GENE', 'VARIANT_CLASS', 'CONS', 'EXON', 'HGVSc',
>         'HGVSp', 'gnomAD_AF', 'SIFT', 'POLYPHEN', 'DB'
>     ]
> ```
More robust to index the field order from the header definition of CSQ then access values using that index, just in case we update VEP in the future and the order changes
</blockquote></details>

Agree that would be better, however the order of the fields are specified in the VEP command, which helps a bit.
`--fields "SYMBOL,VARIANT_CLASS,Consequence,EXON,HGVSc,HGVSp,gnomAD_AF,SIFT,PolyPhen,Existing_variation"`

Are you ok to make this an issue rather than address now?
___
*[resources/home/dnanexus/vcf_handler.py, line 179 at r7](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/11#-MZY3MTJ3Xp9A_AiC8JV:-MZY_tbp5QiV9KLCzdw2:b-dldoqr) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/ae7ae9604a4d97627799bbe204d5da7977a22a05/resources/home/dnanexus/vcf_handler.py#L179)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
>     # get AF values from sample column add to new AF column, convert to %
>     af_index = af_index[0]
>     af_values = vcf_df['SAMPLE'].apply(lambda x: x.split(':')[af_index]).apply(
>         lambda x: '{:.1%}'.format(float(x)))
>     vcf_df.insert(11, 'AF', af_values)
> ```
Do we want to store a % in a field labelled AF? ( it's allele fraction, not allele percentage)
AF is a reserved key with a specific definition: https://samtools.github.io/hts-specs/VCFv4.3.pdf Page 8
</blockquote></details>

It's even worse than that as even before it's converted into a percentage, it's not AF - mutect2 puts it's own calculation in the AF field, rather than providing `AF ... estimated from primary data, not called genotypes`

Have renamed column to something else. (BTW, the scientists call it allele frequency :smile_cat: )

**Review by woook — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/11)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @mattgarner)

___
*[.gitignore, line 1 at r7](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/11#-MZY6zB6AN40STthJARs:-MZYnWhtCOr2nASNQAGn:bhofej8) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/ae7ae9604a4d97627799bbe204d5da7977a22a05/.gitignore#L1)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

No idea_eh
Maybe it's Canadian?
</blockquote></details>

Deleted

**Review by woook — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/11)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @mattgarner)

___
*[.gitignore, line 1 at r7](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/11#-MZY6zB6AN40STthJARs:-MZYnb-U03Xzlm2Y1_9v:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/ae7ae9604a4d97627799bbe204d5da7977a22a05/.gitignore#L1)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

Deleted
</blockquote></details>

Done.

**Comment by mattgarner** [comment]
___
*[resources/home/dnanexus/vcf_handler.py, line 158 at r7](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/11#-MZY2VaXD2g2YpEkIMJB:-MZZnr6h-NfiA4lEM-vJ:b-f4zasg) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/ae7ae9604a4d97627799bbe204d5da7977a22a05/resources/home/dnanexus/vcf_handler.py#L158)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

Agree that would be better, however the order of the fields are specified in the VEP command, which helps a bit.
`--fields "SYMBOL,VARIANT_CLASS,Consequence,EXON,HGVSc,HGVSp,gnomAD_AF,SIFT,PolyPhen,Existing_variation"`

Are you ok to make this an issue rather than address now?
</blockquote></details>

Yes, agreed.

**Comment by mattgarner** [comment]
___
*[resources/home/dnanexus/vcf_handler.py, line 179 at r7](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/11#-MZY3MTJ3Xp9A_AiC8JV:-MZZoMvZ4uVIiYfHmHhX:b62kzlt) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/ae7ae9604a4d97627799bbe204d5da7977a22a05/resources/home/dnanexus/vcf_handler.py#L179)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

It's even worse than that as even before it's converted into a percentage, it's not AF - mutect2 puts it's own calculation in the AF field, rather than providing `AF ... estimated from primary data, not called genotypes`

Have renamed column to something else. (BTW, the scientists call it allele frequency :smile_cat: )
</blockquote></details>

Seems it is frequency rather than fraction after all
```
Allele  frequency  for  each  ALT  allele  in  the  same  order  as  listed(estimated from primary data, not called genotypes)
```
but should still be 0-1 so the point remains.

**Review by mattgarner — APPROVED** [review]
> Reviewed 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/11)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @woook)

___
*[resources/home/dnanexus/vcf_handler.py, line 158 at r7](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/11#-MZY2VaXD2g2YpEkIMJB:-MZZoxK58NmLuDXuWbOP:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/ae7ae9604a4d97627799bbe204d5da7977a22a05/resources/home/dnanexus/vcf_handler.py#L158)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Yes, agreed.
</blockquote></details>

Done
___
*[resources/home/dnanexus/vcf_handler.py, line 179 at r7](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/11#-MZY3MTJ3Xp9A_AiC8JV:-MZZoze99sig1qcI1uDU:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/ae7ae9604a4d97627799bbe204d5da7977a22a05/resources/home/dnanexus/vcf_handler.py#L179)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Seems it is frequency rather than fraction after all
```
Allele  frequency  for  each  ALT  allele  in  the  same  order  as  listed(estimated from primary data, not called genotypes)
```
but should still be 0-1 so the point remains.
</blockquote></details>

Done

**Pull request merged**
