### PR TITLE
Additional panels & previous counts annotation

### PR DESCRIPTION
**Pull request by woook**
- Previous counts annotation added to VCFs and excel
- Excel now has additional panels
- Much excel reformatting
- Added handling of empty VCFs
- VEP moved to being an input rather than an app asset

(The code.sh could probably do with being refactored at some point.)

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/14)

### CODE REVIEW

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/14)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @mattgarner and @woook)

___
*[resources/home/dnanexus/vcf_handler.py, line 103 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/14#-M_a5c1E7iEI69fvNr4t:-M_a5c1E7iEI69fvNr4u:bjkluf7) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/89fe14aa6b10291be600d3a7817f0e1bb4489d8d/resources/home/dnanexus/vcf_handler.py#L103)):*
> ```
>     if vcf_df.empty:
>         print('DataFrame is empty!')
> ```
Is only printing here sufficient? 
Why are we checking if it's empty but not acting on the output?
___
*[resources/home/dnanexus/vcf_handler.py, line 154 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/14#-M_a61KXAGRMSD7KPfgp:-M_a61KXAGRMSD7KPfgq:b8x1yp2) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/89fe14aa6b10291be600d3a7817f0e1bb4489d8d/resources/home/dnanexus/vcf_handler.py#L154)):*
> ```
> all(vcf_df.INFO.str.count(r'\|') == 13),
> ```
call to all() seems unnecessary
 
`assert all(a,b)` <- makes sense to check if both a and b are True
`assert all(a)` <- all() is redundant, same as assert a
___
*[resources/home/dnanexus/vcf_handler.py, line 179 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/14#-M_a7qyy0jqMvRIpD7DY:-M_a7qyy0jqMvRIpD7DZ:bddqz61) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/89fe14aa6b10291be600d3a7817f0e1bb4489d8d/resources/home/dnanexus/vcf_handler.py#L179)):*
> ```
> 13
> ```
This value is hardcoded in a few places, might be easier to maintain if it were moved into a variable which is reused

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/14)* status: all files reviewed, 4 unresolved discussions (waiting on @woook)

___
*[src/code.sh, line 367 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/14#-M_aC5dWBYNzTVb7in97:-M_aC5dWBYNzTVb7in98:b9bzzke) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/89fe14aa6b10291be600d3a7817f0e1bb4489d8d/src/code.sh#L367)):*
> ```Shell
>   ./filter_vep -i /opt/vep/.vep/"${lplfile}" \
>   -o /opt/vep/.vep/"${lplvepfile}" --only_matched --filter \
>   "(gnomAD_AF < 0.10 or not gnomAD_AF) and SYMBOL"
> ```

Feels like all of these should be function(s) calls, but perhaps that's not straightforward.

**Review by woook — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/14)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @mattgarner)

___
*[resources/home/dnanexus/vcf_handler.py, line 103 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/14#-M_a5c1E7iEI69fvNr4t:-M_aD274-kN3WetIh9u0:bu28xu3) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/89fe14aa6b10291be600d3a7817f0e1bb4489d8d/resources/home/dnanexus/vcf_handler.py#L103)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
>     if vcf_df.empty:
>         print('DataFrame is empty!')
> ```
Is only printing here sufficient? 
Why are we checking if it's empty but not acting on the output?
</blockquote></details>

I just put that there so something is output to the log and we can be sure that the empty sheet(s) in the excel were right but unnecessary now so removed.
___
*[resources/home/dnanexus/vcf_handler.py, line 154 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/14#-M_a61KXAGRMSD7KPfgp:-M_aDLSG4wuogrcDjj2-:bybu1km) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/89fe14aa6b10291be600d3a7817f0e1bb4489d8d/resources/home/dnanexus/vcf_handler.py#L154)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> all(vcf_df.INFO.str.count(r'\|') == 13),
> ```
call to all() seems unnecessary
 
`assert all(a,b)` <- makes sense to check if both a and b are True
`assert all(a)` <- all() is redundant, same as assert a
</blockquote></details>

This is a Jethro thing - I believe it was more to help him debug than anything else. Removed.
___
*[resources/home/dnanexus/vcf_handler.py, line 179 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/14#-M_a7qyy0jqMvRIpD7DY:-M_aDUG_EttPqAW0QH9m:b-90qajo) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/89fe14aa6b10291be600d3a7817f0e1bb4489d8d/resources/home/dnanexus/vcf_handler.py#L179)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> 13
> ```
This value is hardcoded in a few places, might be easier to maintain if it were moved into a variable which is reused
</blockquote></details>

Just one place now :) but yeah - have changed to use all (-1).
___
*[src/code.sh, line 367 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/14#-M_aC5dWBYNzTVb7in97:-M_aDmdS306BlrgFW9NM:boar7d8) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/89fe14aa6b10291be600d3a7817f0e1bb4489d8d/src/code.sh#L367)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Feels like all of these should be function(s) calls, but perhaps that's not straightforward.
</blockquote></details>

Yeah, I'm not sure how to best use docker in our apps.

**Review by mattgarner — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/14)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @woook)

**Pull request merged**
