### PR TITLE
First version of app

### PR DESCRIPTION
**Pull request by woook**
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/1)

### CODE REVIEW

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/1)* status: all files reviewed, 6 unresolved discussions (waiting on @woook)

___
*[dxapp.json, line 6 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/1#-MYPdMj7AcBhiuOSXYQB:-MYPdMj7AcBhiuOSXYQC:b-2104uz) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/e0f4d66ff8c370a1db8d43cb812ce5cc6e1efb48/dxapp.json#L6)):*
> ```
>   "properties": {
>     "github release": "dev"
>   },
> ```
```
"properties": {
    "githubRelease": "vx.y.z"
  },
```
___
*[dxapp.json, line 10 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/1#-MYPd_LEBw9U0dSwGCVx:-MYPd_LEBw9U0dSwGCVy:b-qeqxtl) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/e0f4d66ff8c370a1db8d43cb812ce5cc6e1efb48/dxapp.json#L10)):*
> ```
> "1.4.0"
> ```
What is this the version of?
___
*[Readme.md, line 29 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/1#-MYPfLgO0J2CtyZ8DX-9:-MYPfLgO0J2CtyZ8DX-A:bmlnts9) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/e0f4d66ff8c370a1db8d43cb812ce5cc6e1efb48/Readme.md#L29)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> - Filters VCF with bedtools
> - Filters VCF with bcftools
> - Annotates VCF with VEP
> - Filters VCF with VEP
> ```
</details>

What are we removing/keeping with the filters?
___
*[resources/home/dnanexus/mutect2_vcf_2_BSVI_v1.2.0.py, line 173 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/1#-MYPkQCU-UnLq48Zeb49:-MYPkQCV2jcy7aH1Etx4:bclk3ds) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/e0f4d66ff8c370a1db8d43cb812ce5cc6e1efb48/resources/home/dnanexus/mutect2_vcf_2_BSVI_v1.2.0.py#L173)):*
> ```
> ····
> ```
Whitespace
___
*[src/code.sh, line 26 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/1#-MYPlEjb4BPWVjlUl_6o:-MYPlEjb4BPWVjlUl_6p:bdri153) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/e0f4d66ff8c370a1db8d43cb812ce5cc6e1efb48/src/code.sh#L26)):*
> ```
> Number=.
> ```
`Number=\\.`
`.` means any character to sed

Not essential to change, pattern is already specific enough
___
*[src/code.sh, line 100 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/1#-MYPmEPYD6tBx3I8pbJJ:-MYPmEPYD6tBx3I8pbJK:bd7dmgx) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/e0f4d66ff8c370a1db8d43cb812ce5cc6e1efb48/src/code.sh#L100)):*
<details><summary><i alt="summary">Quoted 61 lines of code…</i></summary>

> ```
>   "stable_id match NM_002074 \
>   or stable_id match NM_000760 \
>   or stable_id match NM_005373 \
>   or stable_id match NM_002227 \
>   or stable_id match NM_002524 \
>   or stable_id match NM_022552 \
>   or stable_id match NM_012433 \
>   or stable_id match NM_005896 \
>   or stable_id match NM_002468 \
>   or stable_id match NM_032638 \
>   or stable_id match NM_000222 \
>   or stable_id match NM_001127208 \
>   or stable_id match NM_033632 \
>   or stable_id match NM_002520 \
>   or stable_id match NM_016222 \
>   or stable_id match NM_006060 \
>   or stable_id match NM_181500 \
>   or stable_id match NM_004333 \
>   or stable_id match NM_004456 \
>   or stable_id match NM_170606 \
>   or stable_id match NM_006265 \
>   or stable_id match NM_004972 \
>   or stable_id match NM_016734 \
>   or stable_id match NM_017617 \
>   or stable_id match NM_000314 \
>   or stable_id match NM_005343 \
>   or stable_id match NM_024426 \
>   or stable_id match NM_001165 \
>   or stable_id match NM_000051 \
>   or stable_id match NM_001197104 \
>   or stable_id match NM_005188 \
>   or stable_id match NM_001987 \
>   or stable_id match NM_018638 \
>   or stable_id match NM_033360 \
>   or stable_id match NM_001136023 \
>   or stable_id match NM_005475 \
>   or stable_id match NM_002834 \
>   or stable_id match NM_004119 \
>   or stable_id match NM_002168 \
>   or stable_id match NM_004380 \
>   or stable_id match NM_000546 \
>   or stable_id match NM_001042492 \
>   or stable_id match NM_012448 \
>   or stable_id match NM_139276 \
>   or stable_id match NM_003620 \
>   or stable_id match NM_001195427 \
>   or stable_id match NM_015559 \
>   or stable_id match NM_004343 \
>   or stable_id match NM_004364 \
>   or stable_id match NM_015338 \
>   or stable_id match NM_080425 \
>   or stable_id match NM_001754 \
>   or stable_id match NM_006758 \
>   or stable_id match NM_007194 \
>   or stable_id match NM_001429 \
>   or stable_id match NM_005089 \
>   or stable_id match NM_001123385 \
>   or stable_id match NM_002049 \
>   or stable_id match NM_001042750 \
>   or stable_id match NM_001184772 \
>   or stable_id match NM_001015877"
> ```
</details>

Has this list been checked?  A missing tx here would be very bad.
Do we know that VEP has all of these txs? Does it error if passed a tx it doesn't know about?

**Comment by carmelinacharalambous** [comment]
___
*[src/code.sh, line 100 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/1#-MYPmEPYD6tBx3I8pbJJ:-MYQCmGeC8dkPBd-Bti5:b-3swfzh) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/e0f4d66ff8c370a1db8d43cb812ce5cc6e1efb48/src/code.sh#L100)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
>   "stable_id match NM_002074 \
>   or stable_id match NM_000760 \
>   or stable_id match NM_005373 \
>   or stable_id match NM_002227 \
>   or stable_id match NM_002524 \
>   or stable_id match NM_022552 \
>   or stable_id match NM_012433 \
>   or stable_id match NM_005896 \
>   or stable_id match NM_002468 \
>   or stable_id match NM_032638 \
>   or stable_id match NM_000222 \
>   or stable_id match NM_001127208 \
>   or stable_id match NM_033632 \
>   or stable_id match NM_002520 \
>   or stable_id match NM_016222 \
>   or stable_id match NM_006060 \
>   or stable_id match NM_181500 \
>   or stable_id match NM_004333 \
>   or stable_id match NM_004456 \
>   or stable_id match NM_170606 \
>   or stable_id match NM_006265 \
>   or stable_id match NM_004972 \
>   or stable_id match NM_016734 \
>   or stable_id match NM_017617 \
>   or stable_id match NM_000314 \
>   or stable_id match NM_005343 \
>   or stable_id match NM_024426 \
>   or stable_id match NM_001165 \
>   or stable_id match NM_000051 \
>   or stable_id match NM_001197104 \
>   or stable_id match NM_005188 \
>   or stable_id match NM_001987 \
>   or stable_id match NM_018638 \
>   or stable_id match NM_033360 \
>   or stable_id match NM_001136023 \
>   or stable_id match NM_005475 \
>   or stable_id match NM_002834 \
>   or stable_id match NM_004119 \
>   or stable_id match NM_002168 \
>   or stable_id match NM_004380 \
>   or stable_id match NM_000546 \
>   or stable_id match NM_001042492 \
>   or stable_id match NM_012448 \
>   or stable_id match NM_139276 \
>   or stable_id match NM_003620 \
>   or stable_id match NM_001195427 \
>   or stable_id match NM_015559 \
>   or stable_id match NM_004343 \
>   or stable_id match NM_004364 \
>   or stable_id match NM_015338 \
>   or stable_id match NM_080425 \
>   or stable_id match NM_001754 \
>   or stable_id match NM_006758 \
>   or stable_id match NM_007194 \
>   or stable_id match NM_001429 \
>   or stable_id match NM_005089 \
>   or stable_id match NM_001123385 \
>   or stable_id match NM_002049 \
>   or stable_id match NM_001042750 \
>   or stable_id match NM_001184772 \
>   or stable_id match NM_001015877"
> ```
Has this list been checked?  A missing tx here would be very bad.
Do we know that VEP has all of these txs? Does it error if passed a tx it doesn't know about?
</blockquote></details>

List has been checked all 61 Refseq ID are present and are correct

**Review by woook — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/1)* status: all files reviewed, 6 unresolved discussions (waiting on @mattgarner)

___
*[dxapp.json, line 6 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/1#-MYPdMj7AcBhiuOSXYQB:-MYQFTVv2q_gyCgRAx0n:b-pymdeq) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/e0f4d66ff8c370a1db8d43cb812ce5cc6e1efb48/dxapp.json#L6)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
>   "properties": {
>     "github release": "dev"
>   },
> ```
```
"properties": {
    "githubRelease": "vx.y.z"
  },
```
</blockquote></details>

Whoopse. Should I'll make the githubRelease the same as the app version? 
___
*[dxapp.json, line 10 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/1#-MYPd_LEBw9U0dSwGCVx:-MYQFic53FoiS3M0tJpe:b6981yv) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/e0f4d66ff8c370a1db8d43cb812ce5cc6e1efb48/dxapp.json#L10)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> "1.4.0"
> ```
What is this the version of?
</blockquote></details>

This is the DNAnexus app version 
___
*[Readme.md, line 29 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/1#-MYPfLgO0J2CtyZ8DX-9:-MYQFnkeAErhwRueB1tg:b-lsmj1m) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/e0f4d66ff8c370a1db8d43cb812ce5cc6e1efb48/Readme.md#L29)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> - Filters VCF with bedtools
> - Filters VCF with bcftools
> - Annotates VCF with VEP
> - Filters VCF with VEP
> ```
What are we removing/keeping with the filters?
</blockquote></details>

You could just read the code :p 
Or I could expand. 
___
*[resources/home/dnanexus/mutect2_vcf_2_BSVI_v1.2.0.py, line 173 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/1#-MYPkQCU-UnLq48Zeb49:-MYQFyf9Bzf2-u3s4cje:b32wtd) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/e0f4d66ff8c370a1db8d43cb812ce5cc6e1efb48/resources/home/dnanexus/mutect2_vcf_2_BSVI_v1.2.0.py#L173)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> ····
> ```
Whitespace
</blockquote></details>

ok
___
*[src/code.sh, line 26 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/1#-MYPlEjb4BPWVjlUl_6o:-MYQG4tM1yXX8V0PWHHr:b-qfyffb) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/e0f4d66ff8c370a1db8d43cb812ce5cc6e1efb48/src/code.sh#L26)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> Number=.
> ```
`Number=\\.`
`.` means any character to sed

Not essential to change, pattern is already specific enough
</blockquote></details>

Might as well change it
___
*[src/code.sh, line 100 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/1#-MYPmEPYD6tBx3I8pbJJ:-MYQG7YHAsMBYLw4Vnw_:bxwamev) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/e0f4d66ff8c370a1db8d43cb812ce5cc6e1efb48/src/code.sh#L100)):*
<details><summary><i>Previously, carmelinacharalambous wrote…</i></summary><blockquote>

List has been checked all 61 Refseq ID are present and are correct
</blockquote></details>

Thanks for checking @carmelinacharalambous 

@mattgarner - VEP won't complain if you provide a transcript that it doesn't know for `--transcript_filter` 
However, if I query ensembl 103 (i.e. same version as VEP) with the 61 NM's from this script, ensembl can match every transcript to a gene which confirms that VEP 103 knows these transcripts:

Ensembl query:
http://www.ensembl.org/biomart/martview/31eec3569698e9fb4969f9513ba4edb9?VIRTUALSCHEMANAME=default&ATTRIBUTES=hsapiens_gene_ensembl.default.feature_page.hgnc_symbol|hsapiens_gene_ensembl.default.feature_page.hgnc_id|hsapiens_gene_ensembl.default.feature_page.refseq_mrna&FILTERS=hsapiens_gene_ensembl.default.filters.refseq_mrna."NM_002074,NM_000760,NM_005373,NM_002227,NM_002524,NM_022552,NM_012433,NM_005896,NM_002468,NM_032638,NM_000222,NM_001127208,NM_033632,NM_002520,NM_016222,NM_006060,NM_181500,NM_004333,NM_004456,NM_170606,NM_006265,NM_004972,NM_016734,NM_017617,NM_000314,NM_005343,NM_024426,NM_001165,NM_000051,NM_001197104,NM_005188,NM_001987,NM_018638,NM_033360,NM_001136023,NM_005475,NM_002834,NM_004119,NM_002168,NM_004380,NM_000546,NM_001042492,NM_012448,NM_139276,NM_003620,NM_001195427,NM_015559,NM_004343,NM_004364,NM_015338,NM_080425,NM_001754,NM_006758,NM_007194,NM_001429,NM_005089,NM_001123385,NM_002049,NM_001042750,NM_001184772,NM_001015877"&VISIBLEPANEL=resultspanel

Result:
HGNC symbol	HGNC ID	RefSeq mRNA ID
ATM	HGNC:795	NM_000051
KIT	HGNC:6342	NM_000222
PTEN	HGNC:9588	NM_000314
TP53	HGNC:11998	NM_000546
CSF3R	HGNC:2439	NM_000760
PHF6	HGNC:18145	NM_001015877
NF1	HGNC:7765	NM_001042492
STAG2	HGNC:11355	NM_001042750
BCOR	HGNC:20893	NM_001123385
TET2	HGNC:25941	NM_001127208
NFE2	HGNC:7780	NM_001136023
BIRC3	HGNC:591	NM_001165
BCORL1	HGNC:25657	NM_001184772
SRSF2	HGNC:10783	NM_001195427
KMT2A	HGNC:7132	NM_001197104
EP300	HGNC:3373	NM_001429
RUNX1	HGNC:10471	NM_001754
ETV6	HGNC:3495	NM_001987
GATA1	HGNC:4170	NM_002049
GNB1	HGNC:4396	NM_002074
IDH2	HGNC:5383	NM_002168
JAK1	HGNC:6190	NM_002227
MYD88	HGNC:7562	NM_002468
NPM1	HGNC:7910	NM_002520
NRAS	HGNC:7989	NM_002524
PTPN11	HGNC:9644	NM_002834
PPM1D	HGNC:9277	NM_003620
FLT3	HGNC:3765	NM_004119
BRAF	HGNC:1097	NM_004333
CALR	HGNC:1455	NM_004343
CEBPA	HGNC:1833	NM_004364
CREBBP	HGNC:2348	NM_004380
EZH2	HGNC:3527	NM_004456
JAK2	HGNC:6192	NM_004972
ZRSR2	HGNC:23019	NM_005089
CBL	HGNC:1541	NM_005188
HRAS	HGNC:5173	NM_005343
MPL	HGNC:7217	NM_005373
SH2B3	HGNC:29605	NM_005475
IDH1	HGNC:5382	NM_005896
IKZF1	HGNC:13176	NM_006060
RAD21	HGNC:9811	NM_006265
U2AF1	HGNC:12453	NM_006758
CHEK2	HGNC:16627	NM_007194
SF3B1	HGNC:10768	NM_012433
STAT5B	HGNC:11367	NM_012448
ASXL1	HGNC:18318	NM_015338
SETBP1	HGNC:15573	NM_015559
DDX41	HGNC:18674	NM_016222
PAX5	HGNC:8619	NM_016734
NOTCH1	HGNC:7881	NM_017617
ETNK1	HGNC:24649	NM_018638
DNMT3A	HGNC:2978	NM_022552
WT1	HGNC:12796	NM_024426
GATA2	HGNC:4171	NM_032638
KRAS	HGNC:6407	NM_033360
FBXW7	HGNC:16712	NM_033632
GNAS	HGNC:4392	NM_080425
STAT3	HGNC:11364	NM_139276
KMT2C	HGNC:13726	NM_170606
CUX1	HGNC:2557	NM_181500

**Review by mattgarner — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/1)* status: all files reviewed, 5 unresolved discussions (waiting on @carmelinacharalambous, @mattgarner, and @woook)

___
*[dxapp.json, line 6 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/1#-MYPdMj7AcBhiuOSXYQB:-MYQQ_O13jE_gb2_hJ4_:b-diwz0m) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/e0f4d66ff8c370a1db8d43cb812ce5cc6e1efb48/dxapp.json#L6)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

Whoopse. Should I'll make the githubRelease the same as the app version? 
</blockquote></details>

Yep, that's our usual approach. So the git release and this could both be 1.4.0 if that makes sense.
___
*[Readme.md, line 29 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/1#-MYPfLgO0J2CtyZ8DX-9:-MYQQpQC15s3qVGizELi:bjnmzof) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/e0f4d66ff8c370a1db8d43cb812ce5cc6e1efb48/Readme.md#L29)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

You could just read the code :p 
Or I could expand. 
</blockquote></details>

This is fine. I was really thinking out loud - come across the details in the .sh later, so probably should have removed this comment
Done
___
*[src/code.sh, line 100 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/1#-MYPmEPYD6tBx3I8pbJJ:-MYQR7yiCgbr6QWwIJ_z:bvhlc1z) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/e0f4d66ff8c370a1db8d43cb812ce5cc6e1efb48/src/code.sh#L100)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

Thanks for checking @carmelinacharalambous 

@mattgarner - VEP won't complain if you provide a transcript that it doesn't know for `--transcript_filter` 
However, if I query ensembl 103 (i.e. same version as VEP) with the 61 NM's from this script, ensembl can match every transcript to a gene which confirms that VEP 103 knows these transcripts:

Ensembl query:
http://www.ensembl.org/biomart/martview/31eec3569698e9fb4969f9513ba4edb9?VIRTUALSCHEMANAME=default&ATTRIBUTES=hsapiens_gene_ensembl.default.feature_page.hgnc_symbol|hsapiens_gene_ensembl.default.feature_page.hgnc_id|hsapiens_gene_ensembl.default.feature_page.refseq_mrna&FILTERS=hsapiens_gene_ensembl.default.filters.refseq_mrna."NM_002074,NM_000760,NM_005373,NM_002227,NM_002524,NM_022552,NM_012433,NM_005896,NM_002468,NM_032638,NM_000222,NM_001127208,NM_033632,NM_002520,NM_016222,NM_006060,NM_181500,NM_004333,NM_004456,NM_170606,NM_006265,NM_004972,NM_016734,NM_017617,NM_000314,NM_005343,NM_024426,NM_001165,NM_000051,NM_001197104,NM_005188,NM_001987,NM_018638,NM_033360,NM_001136023,NM_005475,NM_002834,NM_004119,NM_002168,NM_004380,NM_000546,NM_001042492,NM_012448,NM_139276,NM_003620,NM_001195427,NM_015559,NM_004343,NM_004364,NM_015338,NM_080425,NM_001754,NM_006758,NM_007194,NM_001429,NM_005089,NM_001123385,NM_002049,NM_001042750,NM_001184772,NM_001015877"&VISIBLEPANEL=resultspanel

Result:
HGNC symbol	HGNC ID	RefSeq mRNA ID
ATM	HGNC:795	NM_000051
KIT	HGNC:6342	NM_000222
PTEN	HGNC:9588	NM_000314
TP53	HGNC:11998	NM_000546
CSF3R	HGNC:2439	NM_000760
PHF6	HGNC:18145	NM_001015877
NF1	HGNC:7765	NM_001042492
STAG2	HGNC:11355	NM_001042750
BCOR	HGNC:20893	NM_001123385
TET2	HGNC:25941	NM_001127208
NFE2	HGNC:7780	NM_001136023
BIRC3	HGNC:591	NM_001165
BCORL1	HGNC:25657	NM_001184772
SRSF2	HGNC:10783	NM_001195427
KMT2A	HGNC:7132	NM_001197104
EP300	HGNC:3373	NM_001429
RUNX1	HGNC:10471	NM_001754
ETV6	HGNC:3495	NM_001987
GATA1	HGNC:4170	NM_002049
GNB1	HGNC:4396	NM_002074
IDH2	HGNC:5383	NM_002168
JAK1	HGNC:6190	NM_002227
MYD88	HGNC:7562	NM_002468
NPM1	HGNC:7910	NM_002520
NRAS	HGNC:7989	NM_002524
PTPN11	HGNC:9644	NM_002834
PPM1D	HGNC:9277	NM_003620
FLT3	HGNC:3765	NM_004119
BRAF	HGNC:1097	NM_004333
CALR	HGNC:1455	NM_004343
CEBPA	HGNC:1833	NM_004364
CREBBP	HGNC:2348	NM_004380
EZH2	HGNC:3527	NM_004456
JAK2	HGNC:6192	NM_004972
ZRSR2	HGNC:23019	NM_005089
CBL	HGNC:1541	NM_005188
HRAS	HGNC:5173	NM_005343
MPL	HGNC:7217	NM_005373
SH2B3	HGNC:29605	NM_005475
IDH1	HGNC:5382	NM_005896
IKZF1	HGNC:13176	NM_006060
RAD21	HGNC:9811	NM_006265
U2AF1	HGNC:12453	NM_006758
CHEK2	HGNC:16627	NM_007194
SF3B1	HGNC:10768	NM_012433
STAT5B	HGNC:11367	NM_012448
ASXL1	HGNC:18318	NM_015338
SETBP1	HGNC:15573	NM_015559
DDX41	HGNC:18674	NM_016222
PAX5	HGNC:8619	NM_016734
NOTCH1	HGNC:7881	NM_017617
ETNK1	HGNC:24649	NM_018638
DNMT3A	HGNC:2978	NM_022552
WT1	HGNC:12796	NM_024426
GATA2	HGNC:4171	NM_032638
KRAS	HGNC:6407	NM_033360
FBXW7	HGNC:16712	NM_033632
GNAS	HGNC:4392	NM_080425
STAT3	HGNC:11364	NM_139276
KMT2C	HGNC:13726	NM_170606
CUX1	HGNC:2557	NM_181500

</blockquote></details>

Perfect, thanks
Done

**Review by woook — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/1)* status: all files reviewed, 3 unresolved discussions (waiting on @mattgarner and @woook)

___
*[src/code.sh, line 26 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/1#-MYPlEjb4BPWVjlUl_6o:-MYQlxhfAgVUmrDqSnRz:b4a03vc) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/e0f4d66ff8c370a1db8d43cb812ce5cc6e1efb48/src/code.sh#L26)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

Might as well change it
</blockquote></details>

Actually - did you mean change the lines to
`  | sed 's/AD,Number=\\./AD,Number=R/g' \`
`  | sed 's/RPA,Number=\\./RPA,Number=R/g' \`
Because that stops sed from doing what we want...

**Review by woook — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/1)* status: all files reviewed, 3 unresolved discussions (waiting on @mattgarner and @woook)

___
*[src/code.sh, line 26 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/1#-MYPlEjb4BPWVjlUl_6o:-MYQnF4w5lPuqgRK0G-x:b3hadpk) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/e0f4d66ff8c370a1db8d43cb812ce5cc6e1efb48/src/code.sh#L26)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

Actually - did you mean change the lines to
`  | sed 's/AD,Number=\\./AD,Number=R/g' \`
`  | sed 's/RPA,Number=\\./RPA,Number=R/g' \`
Because that stops sed from doing what we want...

</blockquote></details>

I mean when run in the app...
If I run that locally, then it does what we want

**Review by mattgarner — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/1)* status: all files reviewed, 3 unresolved discussions (waiting on @mattgarner and @woook)

___
*[src/code.sh, line 26 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/1#-MYPlEjb4BPWVjlUl_6o:-MYR-UFS6eSUKerW2Rq-:bjwg73x) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/e0f4d66ff8c370a1db8d43cb812ce5cc6e1efb48/src/code.sh#L26)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

I mean when run in the app...
If I run that locally, then it does what we want
</blockquote></details>

```
echo "AD,Number=." | sed s/AD,Number=\\./AD,Number=R/g
AD,Number=R
```
Locally seems fine for me too

`sed s/"AD,Number=\."/"AD,Number=R"/g` should also work - double quote strings, single `\` escape

Or just leave it as it was, I can't see how it could ever match something unintended

**Review by woook — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/1)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @mattgarner)

___
*[dxapp.json, line 6 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/1#-MYPdMj7AcBhiuOSXYQB:-MYR0ZaB8ojJ-FO9Pj8N:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/e0f4d66ff8c370a1db8d43cb812ce5cc6e1efb48/dxapp.json#L6)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Yep, that's our usual approach. So the git release and this could both be 1.4.0 if that makes sense.
</blockquote></details>

Done.
___
*[resources/home/dnanexus/mutect2_vcf_2_BSVI_v1.2.0.py, line 173 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/1#-MYPkQCU-UnLq48Zeb49:-MYR0lP11lcpH5r7IHyu:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/e0f4d66ff8c370a1db8d43cb812ce5cc6e1efb48/resources/home/dnanexus/mutect2_vcf_2_BSVI_v1.2.0.py#L173)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

ok
</blockquote></details>

Done.
___
*[src/code.sh, line 26 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/1#-MYPlEjb4BPWVjlUl_6o:-MYR0nThAwaE--biTsXv:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/e0f4d66ff8c370a1db8d43cb812ce5cc6e1efb48/src/code.sh#L26)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

```
echo "AD,Number=." | sed s/AD,Number=\\./AD,Number=R/g
AD,Number=R
```
Locally seems fine for me too

`sed s/"AD,Number=\."/"AD,Number=R"/g` should also work - double quote strings, single `\` escape

Or just leave it as it was, I can't see how it could ever match something unintended
</blockquote></details>

Done.

**Review by mattgarner — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @woook)

**Pull request merged**
