### PR TITLE
2.3.0 annotate cgpindel

### PR DESCRIPTION
**Pull request by jethror1**
- adds annotation and filtering of cgppindel VCF into the handler app
  - removes the need for the cgppindel_filtering app and uranus annotation workflow
- app now outputs annotated and filtered cgppindel vcf, as well as adding the variants to and extra tab in the xlsx file

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/26)

### CODE REVIEW

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/26)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @jethror1 and @woook)

___
*[resources/home/dnanexus/vcf_handler.py, line 2 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/26#-MoEgBzo8CUQTfF3A00l:-MoEgBzo8CUQTfF3A00m:b-omo1a2) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/d49e3b859dccbbf797c054673afb559651756a1e/resources/home/dnanexus/vcf_handler.py#L2)):*
> ```Python
> """
> Script takes mutect VCFs and:
> ```

Update to also include pindel vcfs

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/26)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @jethror1 and @woook)

___
*[Readme.md, line 78 at r3](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/26#-MoF-SFAEA35_1X3z_cW:-MoF-SFAEA35_1X3z_cX:bb7phvt) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/ec0a50e9db0f393bc0565c3805040024a691ce96/Readme.md#L78)):*
> ```Markdown
>     - Retain variants with gnomAD AF < 0.1
>     - Remove synonymous variants
>     - Filters by transcripts defined in `cpde.sh` for each panel
> ```

typo

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/26)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @Aisha-D and @woook)

___
*[Readme.md, line 78 at r3](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/26#-MoF-SFAEA35_1X3z_cW:-MoIXU870O_QwMT6W0vI:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/ec0a50e9db0f393bc0565c3805040024a691ce96/Readme.md#L78)):*
<details><summary><i>Previously, Aisha-D wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done.
___
*[resources/home/dnanexus/vcf_handler.py, line 2 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/26#-MoEgBzo8CUQTfF3A00l:-MoIXx2DCwdqV0tjl5Y7:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/d49e3b859dccbbf797c054673afb559651756a1e/resources/home/dnanexus/vcf_handler.py#L2)):*
<details><summary><i>Previously, Aisha-D wrote…</i></summary><blockquote>

Update to also include pindel vcfs
</blockquote></details>

Done.

**Review by woook — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/26)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @Aisha-D, @jethror1, and @woook)

___
*[resources/home/dnanexus/vcf_handler.py, line 219 at r5](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/26#-MoYV2Rq303-maWuCZ0U:-MoYV2Rq303-maWuCZ0V:b6hbib8) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/103b6e9d01233a57445c8665ff33e09e58e8e667/resources/home/dnanexus/vcf_handler.py#L219)):*
> ```
>  if "TUMOUR" in vcf_df.columns:
> ```

Is this the best way to determine whether it's pindel VCF? I guess it's fine for now...
___
*[resources/home/dnanexus/vcf_handler.py, line 330 at r5](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/26#-MoYVf2f7GnRfFD_9uMo:-MoYVf2f7GnRfFD_9uMp:bms7drr) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/103b6e9d01233a57445c8665ff33e09e58e8e667/resources/home/dnanexus/vcf_handler.py#L330)):*
> ```
> Read_Depth
> ```

Don't we need to calc depth for pinder? `depth = values.PR + values.NR`

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/26)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @Aisha-D and @woook)

___
*[resources/home/dnanexus/vcf_handler.py, line 219 at r5](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/26#-MoYV2Rq303-maWuCZ0U:-MoZANiVETAn0EfqpvPN:b-kav57j) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/103b6e9d01233a57445c8665ff33e09e58e8e667/resources/home/dnanexus/vcf_handler.py#L219)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

> ```
>  if "TUMOUR" in vcf_df.columns:
> ```

Is this the best way to determine whether it's pindel VCF? I guess it's fine for now...
</blockquote></details>

switch this to use the name passed to the function as I set this to `"pindel"` for reading the vcf from the `-p` argument
___
*[resources/home/dnanexus/vcf_handler.py, line 330 at r5](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/26#-MoYVf2f7GnRfFD_9uMo:-MoZAZiF9YpwW0bcaLWf:bdk5bgd) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/103b6e9d01233a57445c8665ff33e09e58e8e667/resources/home/dnanexus/vcf_handler.py#L330)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

> ```
> Read_Depth
> ```

Don't we need to calc depth for pinder? `depth = values.PR + values.NR`
</blockquote></details>

not sure how I missed this was empty, have now added it to the df from the values

**Review by woook — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/26)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jethror1)

**Pull request merged**
