### PR TITLE
Bug fixing & improvements

### LINKED ISSUE #3: What about homozygous variants?
https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/b01a051766e6cc51e25a10fd958da5f4d1148e8d/resources/home/dnanexus/mutect2_vcf_2_BSVI_v1.2.0.py#L72

What is the effect of the current genotype re-writing on homozygous variants?
Are we in danger of calling something het when it's hom?

### PR DESCRIPTION
**Pull request by jethror1**
- split out AF to separate column
- modifying HGVS naming as scientists are picky
- fix in cell line breaks for old MS excel

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/4)

### CODE REVIEW

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/4)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[resources/home/dnanexus/mutect2_vcf_2_BSVI_v1.2.0.py, line 72 at r4](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/4#-MYjl0CA4bjQjJg0I8zd:-MYjl0CA4bjQjJg0I8ze:bqac65m) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/fb8ceefee714d90c03b18432863eb4e57b457e71/resources/home/dnanexus/mutect2_vcf_2_BSVI_v1.2.0.py#L72)):*
> ```
>         if len(sample[0]) > 3 and sample[0].startswith('0'):
>             # >3 => not 0/1 => modify, startswith 0 => het
>             sample[0] = '0/1'
> ```
This will reject any multiallelic which doesn't contain a ref allele e.g.`1/2/3`
Given that mutect calls with ploidy equal to the number of alleles present I wonder if the former solution was safer, since a `1/1`  would be presented as `1` and so would not enter this block anyway

`1/2/3` is maybe possible, `1/1` does not seem to be

**Review by mattgarner — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/4)* status: all files reviewed, 1 unresolved discussion (waiting on @jethror1)

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/4)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @mattgarner)

___
*[resources/home/dnanexus/mutect2_vcf_2_BSVI_v1.2.0.py, line 72 at r4](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/4#-MYjl0CA4bjQjJg0I8zd:-MYjqzKQC_cbqtI7cxW-:b-msewlw) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/fb8ceefee714d90c03b18432863eb4e57b457e71/resources/home/dnanexus/mutect2_vcf_2_BSVI_v1.2.0.py#L72)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
>         if len(sample[0]) > 3 and sample[0].startswith('0'):
>             # >3 => not 0/1 => modify, startswith 0 => het
>             sample[0] = '0/1'
> ```
This will reject any multiallelic which doesn't contain a ref allele e.g.`1/2/3`
Given that mutect calls with ploidy equal to the number of alleles present I wonder if the former solution was safer, since a `1/1`  would be presented as `1` and so would not enter this block anyway

`1/2/3` is maybe possible, `1/1` does not seem to be
</blockquote></details>

That sounds reasonable, reverted to what we had before

**Review by mattgarner — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jethror1)

**Pull request merged**
